chore: for us we dont need more
Comment out Go linting, testing, and packaging steps in the CI pipeline.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -61,71 +61,71 @@ jobs:
           echo "GIT_TAG=$GIT_TAG"
           echo "GIT_SHA=$GIT_SHA"
 
-  go-lint:
-    name: Lint Go code
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v6
+  # go-lint:
+  #   name: Lint Go code
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v6
 
-      - name: Download TagLib
-        uses: ./.github/actions/download-taglib
-        with:
-          version: ${{ env.CROSS_TAGLIB_VERSION }}
+  #     - name: Download TagLib
+  #       uses: ./.github/actions/download-taglib
+  #       with:
+  #         version: ${{ env.CROSS_TAGLIB_VERSION }}
 
-      - name: golangci-lint
-        uses: golangci/golangci-lint-action@v9
-        with:
-          version: latest
-          problem-matchers: true
-          args: --timeout 2m
+  #     - name: golangci-lint
+  #       uses: golangci/golangci-lint-action@v9
+  #       with:
+  #         version: latest
+  #         problem-matchers: true
+  #         args: --timeout 2m
 
-      - name: Run go goimports
-        run: go run golang.org/x/tools/cmd/goimports@latest -w `find . -name '*.go' | grep -v '_gen.go$' | grep -v '.pb.go$'`
-      - run: go mod tidy
-      - name: Verify no changes from goimports and go mod tidy
-        run: |
-          git status --porcelain
-          if [ -n "$(git status --porcelain)" ]; then
-            echo 'To fix this check, run "make format" and commit the changes'
-            exit 1
-          fi
+  #     - name: Run go goimports
+  #       run: go run golang.org/x/tools/cmd/goimports@latest -w `find . -name '*.go' | grep -v '_gen.go$' | grep -v '.pb.go$'`
+  #     - run: go mod tidy
+  #     - name: Verify no changes from goimports and go mod tidy
+  #       run: |
+  #         git status --porcelain
+  #         if [ -n "$(git status --porcelain)" ]; then
+  #           echo 'To fix this check, run "make format" and commit the changes'
+  #           exit 1
+  #         fi
 
-      - name: Run go generate
-        run: go generate ./...
-      - name: Verify no changes from go generate
-        run: |
-          git status --porcelain
-          if [ -n "$(git status --porcelain)" ]; then
-            echo 'Generated code is out of date. Run "make gen" and commit the changes'
-            exit 1
-          fi
+  #     - name: Run go generate
+  #       run: go generate ./...
+  #     - name: Verify no changes from go generate
+  #       run: |
+  #         git status --porcelain
+  #         if [ -n "$(git status --porcelain)" ]; then
+  #           echo 'Generated code is out of date. Run "make gen" and commit the changes'
+  #           exit 1
+  #         fi
 
-  go:
-    name: Test Go code
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v6
+  # go:
+  #   name: Test Go code
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check out code into the Go module directory
+  #       uses: actions/checkout@v6
 
-      - name: Download TagLib
-        uses: ./.github/actions/download-taglib
-        with:
-          version: ${{ env.CROSS_TAGLIB_VERSION }}
+  #     - name: Download TagLib
+  #       uses: ./.github/actions/download-taglib
+  #       with:
+  #         version: ${{ env.CROSS_TAGLIB_VERSION }}
 
-      - name: Download dependencies
-        run: go mod download
+  #     - name: Download dependencies
+  #       run: go mod download
 
-      - name: Test
-        run: |
-          pkg-config --define-prefix --cflags --libs taglib # for debugging
-          go test -shuffle=on -tags netgo -race ./... -v
+  #     - name: Test
+  #       run: |
+  #         pkg-config --define-prefix --cflags --libs taglib # for debugging
+  #         go test -shuffle=on -tags netgo -race ./... -v
 
-      - name: Test ndpgen
-        run: |
-          cd plugins/cmd/ndpgen
-          go test -shuffle=on -v
-          go build -o ndpgen .
-          ./ndpgen --help
+  #     - name: Test ndpgen
+  #       run: |
+  #         cd plugins/cmd/ndpgen
+  #         go test -shuffle=on -v
+  #         go build -o ndpgen .
+  #         ./ndpgen --help
 
   js:
     name: Test JS code
@@ -160,106 +160,106 @@ jobs:
           cd ui
           npm run build
 
-  i18n-lint:
-    name: Lint i18n files
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v6
-      - run: |
-          set -e
-          for file in resources/i18n/*.json; do
-            echo "Validating $file"
-            if ! jq empty "$file" 2>error.log; then
-              error_message=$(cat error.log)
-              line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
-              echo "::error file=$file,line=$line_number::$error_message"
-              exit 1
-            fi
-          done
-      - run: ./.github/workflows/validate-translations.sh -v
+  # i18n-lint:
+  #   name: Lint i18n files
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #     - run: |
+  #         set -e
+  #         for file in resources/i18n/*.json; do
+  #           echo "Validating $file"
+  #           if ! jq empty "$file" 2>error.log; then
+  #             error_message=$(cat error.log)
+  #             line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
+  #             echo "::error file=$file,line=$line_number::$error_message"
+  #             exit 1
+  #           fi
+  #         done
+  #     - run: ./.github/workflows/validate-translations.sh -v
 
-  build:
-    name: Build
-    needs: [js, go, go-lint, i18n-lint, git-version]
-    strategy:
-      matrix:
-        platform: [ linux/amd64, linux/arm64, linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/386, darwin/amd64, darwin/arm64, windows/amd64, windows/386 ]
-    runs-on: ubuntu-latest
-    env:
-      IS_LINUX: ${{ startsWith(matrix.platform, 'linux/') && 'true' || 'false' }}
-      IS_ARMV5: ${{ matrix.platform == 'linux/arm/v5' && 'true' || 'false' }}
-      GIT_SHA: ${{ needs.git-version.outputs.git_sha }}
-      GIT_TAG: ${{ needs.git-version.outputs.git_tag }}
-    steps:
-      - name: Sanitize platform name
-        id: set-platform
-        run: |
-          PLATFORM=$(echo ${{ matrix.platform }} | tr '/' '_')
-          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
+  # build:
+  #   name: Build
+  #   needs: [js, go, go-lint, i18n-lint, git-version]
+  #   strategy:
+  #     matrix:
+  #       platform: [ linux/amd64, linux/arm64, linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/386, darwin/amd64, darwin/arm64, windows/amd64, windows/386 ]
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     IS_LINUX: ${{ startsWith(matrix.platform, 'linux/') && 'true' || 'false' }}
+  #     IS_ARMV5: ${{ matrix.platform == 'linux/arm/v5' && 'true' || 'false' }}
+  #     GIT_SHA: ${{ needs.git-version.outputs.git_sha }}
+  #     GIT_TAG: ${{ needs.git-version.outputs.git_tag }}
+  #   steps:
+  #     - name: Sanitize platform name
+  #       id: set-platform
+  #       run: |
+  #         PLATFORM=$(echo ${{ matrix.platform }} | tr '/' '_')
+  #         echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
 
-      - uses: actions/checkout@v6
+  #     - uses: actions/checkout@v6
 
-      - name: Prepare Docker Buildx
-        uses: ./.github/actions/prepare-docker
-        id: docker
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          hub_repository: ${{ vars.DOCKER_HUB_REPO }}
-          hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+  #     - name: Prepare Docker Buildx
+  #       uses: ./.github/actions/prepare-docker
+  #       id: docker
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         hub_repository: ${{ vars.DOCKER_HUB_REPO }}
+  #         hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #         hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
 
-      - name: Build Binaries
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: Dockerfile
-          platforms: ${{ matrix.platform }}
-          outputs: |
-            type=local,dest=./output/${{ env.PLATFORM }}
-          target: binary
-          build-args: |
-            GIT_SHA=${{ env.GIT_SHA }}
-            GIT_TAG=${{ env.GIT_TAG }}
-            CROSS_TAGLIB_VERSION=${{ env.CROSS_TAGLIB_VERSION }}
+  #     - name: Build Binaries
+  #       uses: docker/build-push-action@v6
+  #       with:
+  #         context: .
+  #         file: Dockerfile
+  #         platforms: ${{ matrix.platform }}
+  #         outputs: |
+  #           type=local,dest=./output/${{ env.PLATFORM }}
+  #         target: binary
+  #         build-args: |
+  #           GIT_SHA=${{ env.GIT_SHA }}
+  #           GIT_TAG=${{ env.GIT_TAG }}
+  #           CROSS_TAGLIB_VERSION=${{ env.CROSS_TAGLIB_VERSION }}
 
-      - name: Upload Binaries
-        uses: actions/upload-artifact@v6
-        with:
-          name: navidrome-${{ env.PLATFORM }}
-          path: ./output
-          retention-days: 7
+  #     - name: Upload Binaries
+  #       uses: actions/upload-artifact@v6
+  #       with:
+  #         name: navidrome-${{ env.PLATFORM }}
+  #         path: ./output
+  #         retention-days: 7
 
-      - name: Build and push image by digest
-        id: push-image
-        if: env.IS_LINUX == 'true' && env.IS_ARMV5 == 'false'
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: Dockerfile
-          platforms: ${{ matrix.platform }}
-          labels: ${{ steps.docker.outputs.labels }}
-          build-args: |
-            GIT_SHA=${{ env.GIT_SHA }}
-            GIT_TAG=${{ env.GIT_TAG }}
-            CROSS_TAGLIB_VERSION=${{ env.CROSS_TAGLIB_VERSION }}
-          outputs: |
-            type=image,name=ghcr.io/${{ github.repository }},push-by-digest=true,name-canonical=true,push=true
+  #     - name: Build and push image by digest
+  #       id: push-image
+  #       if: env.IS_LINUX == 'true' && env.IS_ARMV5 == 'false'
+  #       uses: docker/build-push-action@v6
+  #       with:
+  #         context: .
+  #         file: Dockerfile
+  #         platforms: ${{ matrix.platform }}
+  #         labels: ${{ steps.docker.outputs.labels }}
+  #         build-args: |
+  #           GIT_SHA=${{ env.GIT_SHA }}
+  #           GIT_TAG=${{ env.GIT_TAG }}
+  #           CROSS_TAGLIB_VERSION=${{ env.CROSS_TAGLIB_VERSION }}
+  #         outputs: |
+  #           type=image,name=ghcr.io/${{ github.repository }},push-by-digest=true,name-canonical=true,push=true
 
-      - name: Export digest
-        if: env.IS_LINUX == 'true' && env.IS_ARMV5 == 'false'
-        run: |
-          mkdir -p /tmp/digests
-          digest="${{ steps.push-image.outputs.digest }}"
-          touch "/tmp/digests/${digest#sha256:}"          
+  #     - name: Export digest
+  #       if: env.IS_LINUX == 'true' && env.IS_ARMV5 == 'false'
+  #       run: |
+  #         mkdir -p /tmp/digests
+  #         digest="${{ steps.push-image.outputs.digest }}"
+  #         touch "/tmp/digests/${digest#sha256:}"          
 
-      - name: Upload digest
-        uses: actions/upload-artifact@v6
-        if: env.IS_LINUX == 'true' && env.IS_ARMV5 == 'false'
-        with:
-          name: digests-${{ env.PLATFORM }}
-          path: /tmp/digests/*
-          if-no-files-found: error
-          retention-days: 1
+  #     - name: Upload digest
+  #       uses: actions/upload-artifact@v6
+  #       if: env.IS_LINUX == 'true' && env.IS_ARMV5 == 'false'
+  #       with:
+  #         name: digests-${{ env.PLATFORM }}
+  #         path: /tmp/digests/*
+  #         if-no-files-found: error
+  #         retention-days: 1
 
   push-manifest-ghcr:
     name: Push to GHCR
@@ -267,7 +267,8 @@ jobs:
       contents: read
       packages: write
     runs-on: ubuntu-latest
-    needs: [build]
+    needs: [js, git-version]
+    # needs: [build]
     env:
       REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
     steps:
@@ -310,110 +311,110 @@ jobs:
             gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact
           done
 
-  msi:
-    name: Build Windows installers
-    needs: [build, git-version]
-    runs-on: ubuntu-24.04
+  # msi:
+  #   name: Build Windows installers
+  #   needs: [build, git-version]
+  #   runs-on: ubuntu-24.04
 
-    steps:
-      - uses: actions/checkout@v6
+  #   steps:
+  #     - uses: actions/checkout@v6
 
-      - uses: actions/download-artifact@v7
-        with:
-          path: ./binaries
-          pattern: navidrome-windows*
-          merge-multiple: true
+  #     - uses: actions/download-artifact@v7
+  #       with:
+  #         path: ./binaries
+  #         pattern: navidrome-windows*
+  #         merge-multiple: true
 
-      - name: Install Wix
-        run: sudo apt-get install -y wixl jq
+  #     - name: Install Wix
+  #       run: sudo apt-get install -y wixl jq
 
-      - name: Build MSI
-        env:
-          GIT_TAG: ${{ needs.git-version.outputs.git_tag }}
-        run: |
-          rm -rf binaries/msi
-          sudo GIT_TAG=$GIT_TAG release/wix/build_msi.sh ${GITHUB_WORKSPACE} 386
-          sudo GIT_TAG=$GIT_TAG release/wix/build_msi.sh ${GITHUB_WORKSPACE} amd64
-          du -h binaries/msi/*.msi
+  #     - name: Build MSI
+  #       env:
+  #         GIT_TAG: ${{ needs.git-version.outputs.git_tag }}
+  #       run: |
+  #         rm -rf binaries/msi
+  #         sudo GIT_TAG=$GIT_TAG release/wix/build_msi.sh ${GITHUB_WORKSPACE} 386
+  #         sudo GIT_TAG=$GIT_TAG release/wix/build_msi.sh ${GITHUB_WORKSPACE} amd64
+  #         du -h binaries/msi/*.msi
 
-      - name: Upload MSI files
-        uses: actions/upload-artifact@v6
-        with:
-          name: navidrome-windows-installers
-          path: binaries/msi/*.msi
-          retention-days: 7
+  #     - name: Upload MSI files
+  #       uses: actions/upload-artifact@v6
+  #       with:
+  #         name: navidrome-windows-installers
+  #         path: binaries/msi/*.msi
+  #         retention-days: 7
 
-  release:
-    name: Package/Release
-    needs: [build, msi]
-    runs-on: ubuntu-latest
-    outputs:
-      package_list: ${{ steps.set-package-list.outputs.package_list }}
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          fetch-depth: 0
-          fetch-tags: true
+  # release:
+  #   name: Package/Release
+  #   needs: [build, msi]
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     package_list: ${{ steps.set-package-list.outputs.package_list }}
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         fetch-depth: 0
+  #         fetch-tags: true
 
-      - uses: actions/download-artifact@v7
-        with:
-          path: ./binaries
-          pattern: navidrome-*
-          merge-multiple: true
+  #     - uses: actions/download-artifact@v7
+  #       with:
+  #         path: ./binaries
+  #         pattern: navidrome-*
+  #         merge-multiple: true
 
-      - run: ls -lR ./binaries
+  #     - run: ls -lR ./binaries
 
-      - name: Set RELEASE_FLAGS for snapshot releases
-        if: env.IS_RELEASE == 'false'
-        run: echo 'RELEASE_FLAGS=--skip=publish --snapshot' >> $GITHUB_ENV
+  #     - name: Set RELEASE_FLAGS for snapshot releases
+  #       if: env.IS_RELEASE == 'false'
+  #       run: echo 'RELEASE_FLAGS=--skip=publish --snapshot' >> $GITHUB_ENV
 
-      - name: Run GoReleaser
-        uses: goreleaser/goreleaser-action@v6
-        with:
-          version: '~> v2'
-          args: "release --clean -f release/goreleaser.yml ${{ env.RELEASE_FLAGS }}"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Run GoReleaser
+  #       uses: goreleaser/goreleaser-action@v6
+  #       with:
+  #         version: '~> v2'
+  #         args: "release --clean -f release/goreleaser.yml ${{ env.RELEASE_FLAGS }}"
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Remove build artifacts
-        run: |
-          ls -l ./dist
-          rm ./dist/*.tar.gz ./dist/*.zip
+  #     - name: Remove build artifacts
+  #       run: |
+  #         ls -l ./dist
+  #         rm ./dist/*.tar.gz ./dist/*.zip
 
-      - name: Upload all-packages artifact
-        uses: actions/upload-artifact@v6
-        with:
-          name: packages
-          path: dist/navidrome_0*
+  #     - name: Upload all-packages artifact
+  #       uses: actions/upload-artifact@v6
+  #       with:
+  #         name: packages
+  #         path: dist/navidrome_0*
 
-      - id: set-package-list
-        name: Export list of generated packages
-        run: |
-          cd dist
-          set +x
-          ITEMS=$(ls navidrome_0* | sed 's/^navidrome_0[^_]*_linux_//' | jq -R -s -c 'split("\n")[:-1]')
-          echo $ITEMS
-          echo "package_list=${ITEMS}" >> $GITHUB_OUTPUT
+  #     - id: set-package-list
+  #       name: Export list of generated packages
+  #       run: |
+  #         cd dist
+  #         set +x
+  #         ITEMS=$(ls navidrome_0* | sed 's/^navidrome_0[^_]*_linux_//' | jq -R -s -c 'split("\n")[:-1]')
+  #         echo $ITEMS
+  #         echo "package_list=${ITEMS}" >> $GITHUB_OUTPUT
 
-  upload-packages:
-    name: Upload Linux PKG
-    runs-on: ubuntu-latest
-    needs: [release]
-    strategy:
-      matrix:
-        item: ${{ fromJson(needs.release.outputs.package_list) }}
-    steps:
-      - name: Download all-packages artifact
-        uses: actions/download-artifact@v7
-        with:
-          name: packages
-          path: ./dist
+  # upload-packages:
+  #   name: Upload Linux PKG
+  #   runs-on: ubuntu-latest
+  #   needs: [release]
+  #   strategy:
+  #     matrix:
+  #       item: ${{ fromJson(needs.release.outputs.package_list) }}
+  #   steps:
+  #     - name: Download all-packages artifact
+  #       uses: actions/download-artifact@v7
+  #       with:
+  #         name: packages
+  #         path: ./dist
 
-      - name: Upload all-packages artifact
-        uses: actions/upload-artifact@v6
-        with:
-          name: navidrome_linux_${{ matrix.item }}
-          path: dist/navidrome_0*_linux_${{ matrix.item }}
+  #     - name: Upload all-packages artifact
+  #       uses: actions/upload-artifact@v6
+  #       with:
+  #         name: navidrome_linux_${{ matrix.item }}
+  #         path: dist/navidrome_0*_linux_${{ matrix.item }}
 
 #  delete-artifacts:
 #    name: Delete unused artifacts
